import faker from 'faker'

import { RepoType, ProfileType } from '../types/githubApi'

export function repoFactory(
  profile: ProfileType,
  overrides?: Partial<RepoType>
): RepoType {
  const id = faker.random.number()
  const node_id = faker.random.uuid()
  const name = faker.random.words()

  return {
    id,
    node_id,
    name,
    full_name: `${profile.login}/${name}`,
    private: faker.random.boolean(),
    owner: {
      login: profile.login,
      id: profile.id,
      node_id: profile.node_id,
      avatar_url: profile.avatar_url,
      gravatar_id: profile.gravatar_id,
      url: profile.url,
      html_url: profile.html_url,
      followers_url: profile.followers_url,
      following_url: profile.following_url,
      gists_url: profile.gists_url,
      starred_url: profile.starred_url,
      subscriptions_url: profile.subscriptions_url,
      organizations_url: profile.organizations_url,
      repos_url: profile.repos_url,
      events_url: profile.events_url,
      received_events_url: profile.received_events_url,
      type: profile.type,
      site_admin: profile.site_admin
    },
    html_url: `https://github.com/${profile.login}/${name}`,
    description: faker.random.boolean() ? faker.random.words() : null,
    fork: false,
    url: `https://api.github.com/repos/${profile.login}/${name}`,
    forks_url: `https://api.github.com/repos/${profile.login}/${name}/forks`,
    keys_url: `https://api.github.com/repos/${profile.login}/${name}/keys{/key_id}`,
    collaborators_url: `https://api.github.com/repos/${profile.login}/${name}/collaborators{/collaborator}`,
    teams_url: `https://api.github.com/repos/${profile.login}/${name}/teams`,
    hooks_url: `https://api.github.com/repos/${profile.login}/${name}/hooks`,
    issue_events_url: `https://api.github.com/repos/${profile.login}/${name}/issues/events{/number}`,
    events_url: `https://api.github.com/repos/${profile.login}/${name}/events`,
    assignees_url: `https://api.github.com/repos/${profile.login}/${name}/assignees{/user}`,
    branches_url: `https://api.github.com/repos/${profile.login}/${name}/branches{/branch}`,
    tags_url: `https://api.github.com/repos/${profile.login}/${name}/tags`,
    blobs_url: `https://api.github.com/repos/${profile.login}/${name}/git/blobs{/sha}`,
    git_tags_url: `https://api.github.com/repos/${profile.login}/${name}/git/tags{/sha}`,
    git_refs_url: `https://api.github.com/repos/${profile.login}/${name}/git/refs{/sha}`,
    trees_url: `https://api.github.com/repos/${profile.login}/${name}/git/trees{/sha}`,
    statuses_url: `https://api.github.com/repos/${profile.login}/${name}/statuses/{sha}`,
    languages_url: `https://api.github.com/repos/${profile.login}/${name}/languages`,
    stargazers_url: `https://api.github.com/repos/${profile.login}/${name}/stargazers`,
    contributors_url: `https://api.github.com/repos/${profile.login}/${name}/contributors`,
    subscribers_url: `https://api.github.com/repos/${profile.login}/${name}/subscribers`,
    subscription_url: `https://api.github.com/repos/${profile.login}/${name}/subscription`,
    commits_url: `https://api.github.com/repos/${profile.login}/${name}/commits{/sha}`,
    git_commits_url: `https://api.github.com/repos/${profile.login}/${name}/git/commits{/sha}`,
    comments_url: `https://api.github.com/repos/${profile.login}/${name}/comments{/number}`,
    issue_comment_url: `https://api.github.com/repos/${profile.login}/${name}/issues/comments{/number}`,
    contents_url: `https://api.github.com/repos/${profile.login}/${name}/contents/{+path}`,
    compare_url: `https://api.github.com/repos/${profile.login}/${name}/compare/{base}...{head}`,
    merges_url: `https://api.github.com/repos/${profile.login}/${name}/merges`,
    archive_url: `https://api.github.com/repos/${profile.login}/${name}/{archive_format}{/ref}`,
    downloads_url: `https://api.github.com/repos/${profile.login}/${name}/downloads`,
    issues_url: `https://api.github.com/repos/${profile.login}/${name}/issues{/number}`,
    pulls_url: `https://api.github.com/repos/${profile.login}/${name}/pulls{/number}`,
    milestones_url: `https://api.github.com/repos/${profile.login}/${name}/milestones{/number}`,
    notifications_url: `https://api.github.com/repos/${profile.login}/${name}/notifications{?since,all,participating}`,
    labels_url: `https://api.github.com/repos/${profile.login}/${name}/labels{/name}`,
    releases_url: `https://api.github.com/repos/${profile.login}/${name}/releases{/id}`,
    deployments_url: `https://api.github.com/repos/${profile.login}/${name}/deployments`,
    created_at: faker.date.past(faker.random.number()).toISOString(),
    updated_at: faker.date.past(faker.random.number()).toISOString(),
    pushed_at: faker.date.past(faker.random.number()).toISOString(),
    git_url: `git://github.com/${profile.login}/${name}.git`,
    ssh_url: `git@github.com:${profile.login}/${name}.git`,
    clone_url: `https://github.com/${profile.login}/${name}.git`,
    svn_url: `https://github.com/${profile.login}/${name}`,
    homepage: faker.random.boolean() ? faker.internet.url() : null,
    size: faker.random.number(),
    stargazers_count: faker.random.number(),
    watchers_count: faker.random.number(),
    language: faker.random.boolean() ? faker.random.word() : null,
    has_issues: faker.random.boolean(),
    has_projects: faker.random.boolean(),
    has_downloads: faker.random.boolean(),
    has_wiki: faker.random.boolean(),
    has_pages: faker.random.boolean(),
    forks_count: faker.random.number(),
    mirror_url: faker.random.boolean() ? faker.internet.url() : null,
    archived: faker.random.boolean(),
    disabled: faker.random.boolean(),
    open_issues_count: faker.random.number(),
    license: null,
    forks: faker.random.number(),
    open_issues: faker.random.number(),
    watchers: faker.random.number(),
    default_branch: 'master',
    ...overrides
  }
}
